### PR TITLE
Third pass -- Stylization Fixes, Updating Manifest File

### PR DESCRIPTION
**Pull request by eveahe**
Added 
- % of sites visited that are running on renewables to top nav and changed top nav styling slightly to accomodate
- take action section to left nav, and additional link info there too.
- removed any stray console.log from js files
- updated favicon to green square
- updated readme with greenbeam screenshot
- updated manifest file to more clearly speak to Greenbeam

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Hi Eve! this looks good - did you assign this to me for a review, before merging in, or do you want some further action?

When I look over this I think I'll need to update the planet friendly web guide page with some more details, and later this week, it may make sense to have a specific landing page available on the green web foundation website, but nether of these should block this being merged in.

**Comment by eveahe** [comment]
Hi Chris! If you have any feedback on the design changes or any other final changes I should make, that would be appreciated! Always good to have another set of eyes.

**Comment by eveahe** [comment]
Ah! I just realized the confusion, yes I meant to assign to you for a review, not as an assignee :)

**Comment by mrchrisadams** [comment]
Hi Eve! This looks good. I'm merging it in, and I'll add the PR for the updated action box

**Review by mrchrisadams — APPROVED** [review]

**Pull request merged**
